//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ph_2_proj_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int stu_id { get; set; }
        public string stu_name { get; set; }
        public Nullable<int> stu_class { get; set; }
    }
}
